// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5HawTUVZgPzf6xyPzNBdsBn2-aha8tbE',
    appId: '1:26112207331:web:a10e025465a6687c1458d6',
    messagingSenderId: '26112207331',
    projectId: 'caffae-vibhav',
    authDomain: 'caffae-vibhav.firebaseapp.com',
    storageBucket: 'caffae-vibhav.appspot.com',
    measurementId: 'G-XJL5ER1Q1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV-B05J_hr7NGxY-IlHUlgrme9tWRmkpo',
    appId: '1:26112207331:android:25210be5c37950081458d6',
    messagingSenderId: '26112207331',
    projectId: 'caffae-vibhav',
    storageBucket: 'caffae-vibhav.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNgJd8g-6E0db2PGnArm5I7ldcxS4QvTg',
    appId: '1:26112207331:ios:84d07d19b8aa926f1458d6',
    messagingSenderId: '26112207331',
    projectId: 'caffae-vibhav',
    storageBucket: 'caffae-vibhav.appspot.com',
    iosBundleId: 'com.example.caffaeVibhav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNgJd8g-6E0db2PGnArm5I7ldcxS4QvTg',
    appId: '1:26112207331:ios:84d07d19b8aa926f1458d6',
    messagingSenderId: '26112207331',
    projectId: 'caffae-vibhav',
    storageBucket: 'caffae-vibhav.appspot.com',
    iosBundleId: 'com.example.caffaeVibhav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5HawTUVZgPzf6xyPzNBdsBn2-aha8tbE',
    appId: '1:26112207331:web:f9424be13ee75df61458d6',
    messagingSenderId: '26112207331',
    projectId: 'caffae-vibhav',
    authDomain: 'caffae-vibhav.firebaseapp.com',
    storageBucket: 'caffae-vibhav.appspot.com',
    measurementId: 'G-R82KVWPH2N',
  );
}
